version: '3'

env:
  REGISTRY: '{{.REGISTRY | default "docker-registry.syscd.tech"}}'

tasks:

  zig-up:
    desc: Run the Zig server
    cmds:
      - zig build server
  
  zig-build-wasm:
    desc: Build the Zig server for wasm
    cmds:
      - zig build -Dtarget=wasm32-emscripten --sysroot zig build -Dtarget=wasm32-emscripten --sysroot (em-config EMSCRIPTEN_ROOT)

  docker-up:
    desc: Run the Docker container
    cmds:
      - docker compose up --remove-orphans

  docker-build:
    desc: Build the Docker image
    cmds:
      - docker build -t {{.REGISTRY}}/yagp:latest .

  docker-push:
    desc: Push the Docker image to registry
    deps:
      - docker-build
    cmds:
      - docker push {{.REGISTRY}}/yagp:latest

  helm-push:
    desc: Push Helm chart to registry
    dir: helm/yagp
    cmds:
      - helm package .
      - helm push yagp-*.tgz oci://{{.REGISTRY}}/charts
      - rm yagp-*.tgz

  kill-zombies:
    desc: Kill zombies based on port
    cmds:
      - PID=$(lsof -t -i :8080) && [ -n "$PID" ] && kill -9 $PID

  tag:
    desc: Get current version and create tag
    cmds:
      - |
        VERSION=$(grep "^version:" helm/yagp/Chart.yaml | sed "s/version: //")
        echo "Current version: $VERSION"
        git tag "v$VERSION"
        git push origin "v$VERSION"