version: '3'

env:
  REGISTRY: '{{.REGISTRY | default "docker-registry.syscd.tech"}}'

tasks:

  zig-up:
    desc: Run the Zig server
    cmds:
      - zig run src/server/server.zig

  docker-up:
    desc: Run the Docker container
    cmds:
      - docker compose up --remove-orphans

  docker-push:
    desc: Push the Docker image to registry
    cmds:
      - docker build -t {{.REGISTRY}}/yagp:latest .
      - docker push {{.REGISTRY}}/yagp:latest

  helm-push:
    desc: Push Helm chart to registry
    dir: helm/yagp
    cmds:
      - helm package .
      - helm push yagp-*.tgz oci://{{.REGISTRY}}/charts
      - rm yagp-*.tgz

  kill-zombies:
    desc: Kill zombies based on port
    cmds:
      - pkill -f 8080

  tag:
    desc: Get current version and create tag
    cmds:
      - |
        VERSION=$(grep "^version:" helm/yagp/Chart.yaml | sed "s/version: //")
        echo "Current version: $VERSION"
        git tag "v$VERSION"
        git push origin "v$VERSION"