apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  gateways:
    - istio-system/dev
    - istio-system/cloudflare
    - istio-system/tailscale
  hosts:
    - yagp.syscd.live
    - yagp.syscd.tech
    - yagp.syscd.xyz
    - yagp.syscd.dev
  http:
    - route:
        - destination:

            host: {{ .Release.Name }}
            port:
                number: {{ .Values.service.port }} 