name: GH Helm

on:
  push:
    branches:
      - main
    paths:
      - 'helm/yagp/**'
  workflow_dispatch:

jobs:
  release-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.13.2

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push Charts
        run: |
          # Package the chart
          helm package "helm/yagp"
          
          # Get the version from Chart.yaml
          version=$(helm show chart "helm/yagp" | grep '^version:' | cut -d' ' -f2)
          
          # Push to GHCR
          helm push yagp-${version}.tgz "oci://ghcr.io/yurifrl/charts"